-- ============================================================
-- Terminal 17 - Ad-Hoc Queries (Run in SQL Developer)
-- ============================================================

-- ── BASIC QUERIES ──

-- 1. List all bookings by customer 'Ronaldo'
SELECT b.* FROM BOOKING b
JOIN CUSTOMER c ON b.CUSTOMER_ID = c.CUSTOMER_ID
WHERE LOWER(c.CUSTOMER_NAME) = 'ronaldo';

-- 2. Show all complaints with status 'Pending'
SELECT * FROM COMPLAINT WHERE LOWER(COMPLAINT_STATUS) = 'pending';

-- 3. Display all schedules for a specific date (2026-07-09)
SELECT * FROM SCHEDULE
WHERE TRUNC(DEPARTURE_DATE_TIME) = TO_DATE('2026-07-09', 'YYYY-MM-DD');

-- 4. List all buses with their assigned driver names
SELECT b.*, d.DRIVER_NAME FROM BUS b
LEFT JOIN DRIVER d ON b.DRIVER_ID = d.DRIVER_ID;

-- 5. Find all unclaimed lost items
SELECT * FROM LOST_ITEM WHERE LOWER(CLAIM_STATUS) = 'unclaimed';

-- ── JOIN QUERIES ──

-- 6. Booking details with customer name, route, schedule
SELECT b.BOOKING_ID, c.CUSTOMER_NAME, r.ROUTE_NAME, r.DEPARTURE_LOCATION, r.ARRIVAL_LOCATION, s.DEPARTURE_DATE_TIME, b.TOTAL_PASSENGER, b.TOTAL_FARE, b.BOOKING_STATUS
FROM BOOKING b
JOIN CUSTOMER c ON b.CUSTOMER_ID = c.CUSTOMER_ID
JOIN SCHEDULE s ON b.SCHEDULE_ID = s.SCHEDULE_ID
JOIN ROUTE r ON s.ROUTE_ID = r.ROUTE_ID;

-- 7. Complaints with customer name and bus number
SELECT co.COMPLAINT_ID, cu.CUSTOMER_NAME, b.BUS_NUMBER, co.COMPLAINT_TITLE, co.COMPLAINT_CATEGORY, co.COMPLAINT_STATUS, co.COMPLAINT_DATE_TIME
FROM COMPLAINT co
LEFT JOIN CUSTOMER cu ON co.CUSTOMER_ID = cu.CUSTOMER_ID
LEFT JOIN BUS b ON co.BUS_ID = b.BUS_ID;

-- 8. Schedules with route name, bus number, driver name
SELECT s.SCHEDULE_ID, r.ROUTE_NAME, b.BUS_NUMBER, d.DRIVER_NAME, s.DEPARTURE_DATE_TIME
FROM SCHEDULE s
JOIN ROUTE r ON s.ROUTE_ID = r.ROUTE_ID
JOIN BUS b ON s.BUS_ID = b.BUS_ID
JOIN DRIVER d ON s.DRIVER_ID = d.DRIVER_ID;

-- 9. Customer referrals (customers with referrer name)
SELECT c.CUSTOMER_NAME AS CUSTOMER, r.CUSTOMER_NAME AS REFERRED_BY
FROM CUSTOMER c
LEFT JOIN CUSTOMER r ON c.REFERRED_BY = r.CUSTOMER_ID;

-- 10. Lost items with customer name and bus number
SELECT l.*, c.CUSTOMER_NAME, b.BUS_NUMBER
FROM LOST_ITEM l
LEFT JOIN CUSTOMER c ON l.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN BUS b ON l.BUS_ID = b.BUS_ID;

-- ── AGGREGATION QUERIES ──

-- 11. Count bookings per customer
SELECT c.CUSTOMER_NAME, COUNT(b.BOOKING_ID) AS TOTAL_BOOKINGS
FROM CUSTOMER c
LEFT JOIN BOOKING b ON c.CUSTOMER_ID = b.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME ORDER BY TOTAL_BOOKINGS DESC;

-- 12. Count complaints per status
SELECT COMPLAINT_STATUS, COUNT(*) AS TOTAL
FROM COMPLAINT GROUP BY COMPLAINT_STATUS ORDER BY TOTAL DESC;

-- 13. Total passengers per route
SELECT r.ROUTE_NAME, SUM(b.TOTAL_PASSENGER) AS TOTAL_PASSENGERS
FROM BOOKING b
JOIN SCHEDULE s ON b.SCHEDULE_ID = s.SCHEDULE_ID
JOIN ROUTE r ON s.ROUTE_ID = r.ROUTE_ID
GROUP BY r.ROUTE_NAME ORDER BY TOTAL_PASSENGERS DESC;

-- 14. Bookings per month (for chart)
SELECT TO_CHAR(s.DEPARTURE_DATE_TIME, 'YYYY-MM') AS MONTH, COUNT(*) AS BOOKINGS
FROM BOOKING b
JOIN SCHEDULE s ON b.SCHEDULE_ID = s.SCHEDULE_ID
GROUP BY TO_CHAR(s.DEPARTURE_DATE_TIME, 'YYYY-MM') ORDER BY MONTH;

-- 15. Drivers per employment status
SELECT EMPLOYMENT_STATUS, COUNT(*) AS TOTAL
FROM DRIVER GROUP BY EMPLOYMENT_STATUS;

-- ── FILTER QUERIES ──

-- 16. Customers who filed at least one complaint
SELECT DISTINCT c.CUSTOMER_ID, c.CUSTOMER_NAME, c.EMAIL
FROM CUSTOMER c
JOIN COMPLAINT co ON c.CUSTOMER_ID = co.CUSTOMER_ID;

-- 17. Active & fit drivers
SELECT * FROM DRIVER
WHERE LOWER(HEALTH_STATUS) = 'fit' AND LOWER(EMPLOYMENT_STATUS) = 'active';

-- 18. Schedules with available seats (not fully booked)
SELECT s.SCHEDULE_ID, r.ROUTE_NAME, b.TOTAL_SEATS,
       (SELECT COUNT(*) FROM BOOKING bk WHERE bk.SCHEDULE_ID = s.SCHEDULE_ID) AS BOOKED,
       b.TOTAL_SEATS - (SELECT COUNT(*) FROM BOOKING bk WHERE bk.SCHEDULE_ID = s.SCHEDULE_ID) AS AVAILABLE
FROM SCHEDULE s
JOIN ROUTE r ON s.ROUTE_ID = r.ROUTE_ID
JOIN BUS b ON s.BUS_ID = b.BUS_ID
WHERE b.TOTAL_SEATS > (SELECT COUNT(*) FROM BOOKING bk WHERE bk.SCHEDULE_ID = s.SCHEDULE_ID);

-- 19. Routes departing from Shah Alam
SELECT * FROM ROUTE WHERE LOWER(DEPARTURE_LOCATION) = 'shah alam';

-- 20. Lost items: claimed vs unclaimed count
SELECT CLAIM_STATUS, COUNT(*) AS TOTAL
FROM LOST_ITEM GROUP BY CLAIM_STATUS;

-- ── SUBQUERY QUERIES ──

-- 21. Customers with more than 2 bookings
SELECT c.CUSTOMER_NAME, COUNT(b.BOOKING_ID) AS BOOKING_COUNT
FROM CUSTOMER c
JOIN BOOKING b ON c.CUSTOMER_ID = b.CUSTOMER_ID
GROUP BY c.CUSTOMER_NAME HAVING COUNT(b.BOOKING_ID) > 2;

-- 22. Routes with no schedules assigned
SELECT * FROM ROUTE
WHERE ROUTE_ID NOT IN (SELECT DISTINCT ROUTE_ID FROM SCHEDULE);

-- 23. Bus with the most bookings
SELECT b.BUS_NUMBER, COUNT(bk.BOOKING_ID) AS BOOKING_COUNT
FROM BOOKING bk
JOIN SCHEDULE s ON bk.SCHEDULE_ID = s.SCHEDULE_ID
JOIN BUS b ON s.BUS_ID = b.BUS_ID
GROUP BY b.BUS_NUMBER ORDER BY BOOKING_COUNT DESC FETCH FIRST 1 ROW ONLY;

-- 24. Drivers with no bus assignment
SELECT * FROM DRIVER
WHERE DRIVER_ID NOT IN (SELECT DISTINCT DRIVER_ID FROM BUS WHERE DRIVER_ID IS NOT NULL);

-- ── DATE QUERIES ──

-- 25. Bookings made in the last 7 days
SELECT * FROM BOOKING
WHERE BOOKING_DATE_TIME >= SYSDATE - 7;

-- 26. Upcoming schedules (future departures)
SELECT s.SCHEDULE_ID, r.ROUTE_NAME, b.BUS_NUMBER, d.DRIVER_NAME, s.DEPARTURE_DATE_TIME
FROM SCHEDULE s
JOIN ROUTE r ON s.ROUTE_ID = r.ROUTE_ID
JOIN BUS b ON s.BUS_ID = b.BUS_ID
JOIN DRIVER d ON s.DRIVER_ID = d.DRIVER_ID
WHERE s.DEPARTURE_DATE_TIME > SYSDATE ORDER BY s.DEPARTURE_DATE_TIME;

-- 27. Complaints filed this month
SELECT * FROM COMPLAINT
WHERE TRUNC(COMPLAINT_DATE_TIME, 'MM') = TRUNC(SYSDATE, 'MM');

-- 28. Lost items reported this week
SELECT * FROM LOST_ITEM
WHERE LOST_DATE >= TRUNC(SYSDATE, 'IW');
