-- ============================================================
-- Terminal 17 Management System - Database Setup Script
-- Run this in Oracle SQL Developer or sqlplus
-- ============================================================

-- ─── DROP existing tables (FK-safe order) ───
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOKING CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SCHEDULE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE COMPLAINT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE LOST_ITEM CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE NOTIFICATION CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE BUS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ADMIN CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE DRIVER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE ROUTE CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- ─── CUSTOMER ───
CREATE TABLE CUSTOMER (
    CUSTOMER_ID   NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    GENDER        VARCHAR2(10),
    DATE_OF_BIRTH DATE,
    EMAIL         VARCHAR2(100),
    PHONE_NUMBER  VARCHAR2(15),
    PASSWORD      VARCHAR2(255),
    REFERRED_BY   NUMBER REFERENCES CUSTOMER(CUSTOMER_ID)
);

-- ─── DRIVER ───
CREATE TABLE DRIVER (
    DRIVER_ID           NUMBER PRIMARY KEY,
    DRIVER_NAME         VARCHAR2(100) NOT NULL,
    GENDER              VARCHAR2(10),
    DATE_OF_BIRTH       DATE,
    EMAIL               VARCHAR2(100),
    PHONE_NUMBER        VARCHAR2(15),
    PASSWORD            VARCHAR2(255),
    IC_NUMBER           VARCHAR2(20),
    LICENSE_NUMBER      VARCHAR2(50),
    EXPERIENCE_YEARS    NUMBER,
    HEALTH_STATUS       VARCHAR2(50),
    SAFETY_CERTIFICATION VARCHAR2(100),
    EMPLOYMENT_STATUS   VARCHAR2(50)
);

-- ─── ROUTE ───
CREATE TABLE ROUTE (
    ROUTE_ID          NUMBER PRIMARY KEY,
    ROUTE_NAME        VARCHAR2(100),
    DEPARTURE_LOCATION VARCHAR2(100),
    ARRIVAL_LOCATION  VARCHAR2(100),
    DISTANCE_KM       NUMBER(6,2),
    ESTIMATED_DURATION VARCHAR2(50),
    CURRENT_LOCATION  VARCHAR2(100),
    BUS_NUMBER        VARCHAR2(50)
);

-- ─── ADMIN ───
CREATE TABLE ADMIN (
    ADMIN_ID    NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER UNIQUE REFERENCES CUSTOMER(CUSTOMER_ID),
    CREATED_AT  DATE DEFAULT SYSDATE
);

-- ─── BUS ───
CREATE TABLE BUS (
    BUS_ID       NUMBER PRIMARY KEY,
    DRIVER_ID    NUMBER REFERENCES DRIVER(DRIVER_ID),
    BUS_NUMBER   VARCHAR2(20),
    PLATE_NUMBER VARCHAR2(20),
    TOTAL_SEATS  NUMBER,
    BUS_STATUS   VARCHAR2(50)
);

-- ─── SCHEDULE ───
CREATE TABLE SCHEDULE (
    SCHEDULE_ID         NUMBER PRIMARY KEY,
    BUS_ID              NUMBER REFERENCES BUS(BUS_ID),
    DRIVER_ID           NUMBER REFERENCES DRIVER(DRIVER_ID),
    ROUTE_ID            NUMBER REFERENCES ROUTE(ROUTE_ID),
    DEPARTURE_DATE_TIME DATE,
    ARRIVAL_DATE_TIME   DATE
);

-- ─── BOOKING ───
CREATE TABLE BOOKING (
    BOOKING_ID        NUMBER PRIMARY KEY,
    CUSTOMER_ID       NUMBER REFERENCES CUSTOMER(CUSTOMER_ID),
    SCHEDULE_ID       NUMBER REFERENCES SCHEDULE(SCHEDULE_ID),
    BOOKING_DATE_TIME DATE,
    TOTAL_PASSENGER   NUMBER,
    TOTAL_FARE        NUMBER(10,2),
    BOOKING_STATUS    VARCHAR2(50),
    PAYMENT_STATUS    VARCHAR2(50)
);

-- ─── COMPLAINT ───
CREATE TABLE COMPLAINT (
    COMPLAINT_ID          NUMBER PRIMARY KEY,
    CUSTOMER_ID           NUMBER REFERENCES CUSTOMER(CUSTOMER_ID),
    BUS_ID                NUMBER,
    COMPLAINT_TITLE       VARCHAR2(100),
    COMPLAINT_CATEGORY    VARCHAR2(50),
    COMPLAINT_DESCRIPTION VARCHAR2(1000),
    COMPLAINT_STATUS      VARCHAR2(50),
    COMPLAINT_DATE_TIME   DATE
);

-- ─── LOST_ITEM ───
CREATE TABLE LOST_ITEM (
    LOST_ITEM_ID    NUMBER PRIMARY KEY,
    CUSTOMER_ID     NUMBER REFERENCES CUSTOMER(CUSTOMER_ID),
    BUS_ID          NUMBER REFERENCES BUS(BUS_ID),
    ITEM_NAME       VARCHAR2(100),
    ITEM_CATEGORY   VARCHAR2(50),
    ITEM_DESCRIPTION VARCHAR2(1000),
    LOST_DATE       DATE,
    CLAIM_STATUS    VARCHAR2(50)
);

-- ─── SEED DATA ───

-- Customers
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, GENDER, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES (1, 'Admin Terminal', 'Male', TO_DATE('1990-01-01', 'YYYY-MM-DD'), 'admin@uitm.edu.my', '0123456789', 'password123');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, GENDER, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES (135, 'Ronaldo', 'Male', TO_DATE('1985-02-05', 'YYYY-MM-DD'), 'ronaldo@uitm.edu.my', '0126787677', 'siu');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, GENDER, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES (374, 'Neymar', 'Male', TO_DATE('1992-02-05', 'YYYY-MM-DD'), 'ney@email.com', '0123456787', 'ney');

INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, GENDER, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, PASSWORD)
VALUES (762, 'Haaland', 'Male', TO_DATE('2000-07-21', 'YYYY-MM-DD'), 'haaland@email.com', '013-6767676', 'h123');

-- Admin
INSERT INTO ADMIN (ADMIN_ID, CUSTOMER_ID, CREATED_AT)
VALUES (12, 1, SYSDATE);

-- Drivers
INSERT INTO DRIVER (DRIVER_ID, DRIVER_NAME, GENDER, DATE_OF_BIRTH, EMAIL, PHONE_NUMBER, PASSWORD,
                    IC_NUMBER, LICENSE_NUMBER, EXPERIENCE_YEARS, HEALTH_STATUS, SAFETY_CERTIFICATION, EMPLOYMENT_STATUS)
VALUES (61, 'Zaim Hanis', 'Male', TO_DATE('1967-07-06', 'YYYY-MM-DD'), 'zaim67@email.com', '0167676767', 'zaim67',
        '6767676767', '12367', 67, 'Fit', 'Certified', 'Active');

COMMIT;
/

-- ─── SEQUENCE ───
CREATE SEQUENCE BOOKING_SEQ START WITH 1 INCREMENT BY 1;
